### ISSUE TITLE
I wish the mouse wasn't hidden when writing on the card.

### ISSUE THREAD

**Issue by Aveeno1432** [Rytisgit/Anki-StylusDraw#15]
Hello. Thank you for making a great addon!

I wish the mouse wasn't hidden when writing on the card. I use Windows 11 and my input device is a XP-Pen tablet and when writing on a card, the mouse cursor is hidden and blinks, which is annoying. I have attached a video about this. It would be nice if the mouse cursor stayed there instead of being hidden.

if you don't mind, could you consider the requst?

Thank you so much 

* Please understand that the video screen is a little dark due to the anti-spy film on the monitor.

https://github.com/Rytisgit/Anki-StylusDraw/assets/149929279/506e784c-36ba-43cb-ab8d-84e82f32d654

**Comment by Rytisgit** [comment]
Good to hear that you like it. I will look into adding a setting for this.

**Comment by Rytisgit** [comment]
@Aveeno1432 I've added the new setting, enjoy, and if you don't mind add a star to the GitHub repo.

**Comment by Aveeno1432** [comment]
> @Aveeno1432 I've added the new setting, enjoy, and if you don't mind add a star to the GitHub repo.

 You are truly amazing! This was a feature I really wanted. Thanks for adding it. I just added a star to my GitHub repo. Have a good day!
