### ISSUE TITLE
Canvas background colour

### ISSUE THREAD

**Issue by Davemi123** [Rytisgit/Anki-StylusDraw#18]
Can a canvas background colour option be added?

**Comment by Rytisgit** [comment]
the canvas covers the whole screen and is transparent so you can see your cards in anki. Which part should be coloured?

**Comment by Davemi123** [comment]
Just need to have the canvas coloured when you make it smaller, do it's like having 2 windows on the card

**Comment by Rytisgit** [comment]
I've added a background color selection to the toolbar and canvas location settings. Make sure to set the alpha channel to make the color more transparent if you need to. it will change the color of the canvas in both the full and the small screen modes, if you use the small mode it's only colored within the canvas borders, I think that's fine, right? Add a star if you haven't yet! 
![image](https://github.com/Rytisgit/Anki-StylusDraw/assets/36188103/8d17720e-ea7a-4cc4-a6fb-2367d176bfe2)

**Comment by Davemi123** [comment]
Amazing!!! Thank you so much for your help :)

**Comment by Davemi123** [comment]
![image](https://github.com/Rytisgit/Anki-StylusDraw/assets/34933928/77f0f99b-672c-4730-a6fb-6143da6cfb6f)
This is what my reviews look like now, it's like having a little answer window/drawing pad whilst answering my cards!

**Comment by Davemi123** [comment]
Thank you so much!
    On Thursday, 15 February 2024 at 14:24:12 GMT, Rytis Petronis ***@***.***> wrote:  
 
 


I've added a background color selection to the toolbar and canvas location settings. Make sure to set the alpha channel to make the color more transparent if you need to. it will change the color of the canvas in both the full and the small screen modes, if you use the small mode it's only colored within the canvas borders, I think that's fine, right? Add a star if you haven't yet!
image.png (view on web)
