### ISSUE TITLE
区域画布长宽调整bug

### ISSUE THREAD

**Issue by cr26696** [Rytisgit/Anki-StylusDraw#21]
![image](https://github.com/Rytisgit/Anki-StylusDraw/assets/30682600/d9ec7ea4-c9bd-4dc6-8ff1-4219cb604d5c)
出现了两个名字相同的设置字段Non-fullscreen canvas width，并且点击保存会自动交换长宽值：
点击accept前
![image](https://github.com/Rytisgit/Anki-StylusDraw/assets/30682600/5aa533c5-dcb6-4742-8267-d6dc669eba03)
点击accept后
![image](https://github.com/Rytisgit/Anki-StylusDraw/assets/30682600/ac1d7c7a-d082-4c5d-b077-e6cf9bb2afa0)

**Comment by Rytisgit** [comment]
谢谢.
