### ISSUE TITLE
Randomly unable to draw(only single dots) after a random combination of button and shortcut to toggle visibility

### ISSUE THREAD

**Issue by Rytisgit** [Rytisgit/Anki-StylusDraw#24]
When the toggle invisibility button is disabled using the shortcut key (comma), then when we re-enable visibility, by either clicking or shortcut key, we can no longer use the pen (until we go back to home (deck) and come back to 'study now' again), when we try to write, only the first click is drawn as a dot and then with the drag nothing is drawn, so if I try to draw many lines there will be many dots on the screen, at the point from where I tried to draw a line, please look into that.

**Comment by CaptainDead** [comment]
Thanks for adding the issue here, this issue doesn't happen every time but sometimes when we use the shortcut key. here's a video of this bug I recreated - 
https://youtu.be/yGfDaFZvEeE

**Comment by Rytisgit** [comment]
Thanks for the info!

**Comment by CaptainDead** [comment]
You're amazing, u fixed it this quick, thanks💯🙏🔥
