### ISSUE TITLE
Cannot scroll the page with a pen

### ISSUE THREAD

**Issue by Leiyi548** [Rytisgit/Anki-StylusDraw#32]
I use the Gaoman digital board for learning, and my card content is long and needs to be scrolled. I can't scroll directly with a pen.

**Comment by Rytisgit** [comment]
if you hide the drawing board you should be able to scroll instead of drawing with a pen: 
![image](https://github.com/user-attachments/assets/73f2cdf8-8619-40a8-9458-5d0da6f01c9f)

**Comment by Leiyi548** [comment]
> if you hide the drawing board you should be able to scroll instead of drawing with a pen: ![image](https://private-user-images.githubusercontent.com/36188103/377660271-73f2cdf8-8619-40a8-9458-5d0da6f01c9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTYwMjQsIm5iZiI6MTcyOTIxNTcyNCwicGF0aCI6Ii8zNjE4ODEwMy8zNzc2NjAyNzEtNzNmMmNkZjgtODYxOS00MGE4LTk0NTgtNWQwZGE2ZjAxYzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxNDIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4N2UzM2ZhMTdkMGQyNjE4MTdmMTM4YTkwZTI1NWZkY2UyMjI4ZGE2MGYwNzFhNzZlMWZmYjY4MjIzZDdjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZvDjkA6NHzGWh7IO3zBHmI7dywBOu-MWCpjG1lvy2nU)

Cannot roll with a pen

**Comment by Rytisgit** [comment]
There are a few options - first I would look through your Gaoman software to see what buttons you can rebind and set to scrolling mode. This is a common feature, and it's how I had my pen set up. You can also use the vertical scroll bar on the right by simply dragging it with the pen when the drawing mode is hidden. Finally you can use up/down arrows or page up/page down to scroll without the scroll wheel.

**Comment by Leiyi548** [comment]
I switched to using Ankidroid in the lightning simulator
