### ISSUE TITLE
Hide the UI 

### ISSUE THREAD

**Issue by orangelover12** [Rytisgit/Anki-StylusDraw#7]
I would like to disable the function to hide the UI while drawing. Is there any way? It's a little bit annoying that it keeps blinking while I'm writing. :'( Any help is really appreciated. Thank you so much for awesome add-on

**Comment by Rytisgit** [comment]
Yep, it's possible, I was thinking to add the option for that earlier, just didn't do it. I'll do an update with that option soon.

**Comment by orangelover12** [comment]
Thank you so much, you are the savior of my grades!  I'm waiting for an update. I wish you all the best.
